name: Init

on: push

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Optimize Network Settings
        run: |
            sudo sysctl -w net.core.default_qdisc=fq \
            && sudo sysctl -w net.ipv4.tcp_congestion_control=bbr \
            && sudo sysctl -w net.ipv4.tcp_window_scaling=1 \
            && sudo sysctl -w net.ipv4.ip_forward=1 \
            && sudo sysctl -w net.core.rmem_max=1000000000 \
            && sudo sysctl -w net.core.wmem_max=1000000000 \
            && sudo sysctl -p
            

      - name: Install Deps and Initialization
        run: |
            sudo apt-get update && sudo apt-get -y install git curl wget unzip libcurl4-openssl-dev build-essential nodejs npm ffmpeg
            sudo git clone https://github.com/TannerGabriel/discord-bot
            sudo git clone https://github.com/nawka12/AiChanBot
            sudo touch .env
            sudo chmod -R 777 ./.env
            sudo echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN_MOONAROH }}" >> .env
            sudo mv ./.env ./discord-bot
            sudo touch .env
            sudo chmod -R 777 ./.env
            sudo echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN_AICHAN }}" >> .env
            sudo echo "OPENAI_ORG=${{ secrets.OPENAI_ORG }}" >> .env
            sudo echo "OPENAI_KEY=${{ secrets.OPENAI_KEY }}" >> .env
            sudo mv ./.env ./AiChanBot

      - name: Setup Moonaroh
        working-directory: ./discord-bot
        run: |
            sudo pwd
            sudo npm i
            sudo node index.js &

      - name: Setup AiChan
        working-directory: ./AiChanBot
        continue-on-error: true
        timeout-minutes: 310
        run: |
            sudo pwd
            sudo npm i
            sudo node index.js

      - name: Always Check
        if: always()
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACTIONS_PAT }}
          event-type: restart
          client-payload: '{"runid": "${{ github.run_id }}"}'
