name: Init

on: push

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Optimize Network Settings
        run: |
            sudo sysctl -w net.core.default_qdisc=fq \
            && sudo sysctl -w net.ipv4.tcp_congestion_control=bbr \
            && sudo sysctl -w net.ipv4.tcp_window_scaling=1 \
            && sudo sysctl -w net.ipv4.tcp_reordering=15 \
            && sudo sysctl -w net.ipv4.tcp_fastopen=3 \
            && sudo sysctl -w net.ipv4.ip_forward=1 \
            && sudo sysctl -w net.core.rmem_max=67108864 \
            && sudo sysctl -w net.core.wmem_max=67108864 \
            && sudo sysctl -w net.core.netdev_max_backlog=2000 \
            && sudo sysctl -p

      - name: Install Deps
        run: |
            sudo apt-get update && sudo apt-get -y install git curl wget unzip libcurl4-openssl-dev build-essential nodejs npm ffmpeg python3-dev python3-babel python3-venv uwsgi uwsgi-plugin-python3 libxslt-dev zlib1g-dev libffi-dev libssl-dev

      - name: Setup Moonaroh AiChan
        continue-on-error: true
        timeout-minutes: 310
        run: |
            sudo pwd
            sudo git clone https://github.com/TannerGabriel/discord-bot
            cd discord-bot
            sudo touch .env
            sudo chmod -R 777 ./.env
            sudo echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN_MOONAROH }}" >> .env
            sudo npm i
            sudo node index.js &
            cd ..
            sudo git clone https://github.com/nawka12/AiChanBot
            cd AiChanBot
            sudo touch .env
            sudo chmod -R 777 ./.env
            sudo echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN_AICHAN }}" >> .env
            sudo echo "OPENAI_ORG=${{ secrets.OPENAI_ORG }}" >> .env
            sudo echo "OPENAI_KEY=${{ secrets.OPENAI_KEY }}" >> .env
            sudo -H -u searxng -i
            sudo git clone "https://github.com/searxng/searxng" \
            && "/usr/local/searxng/searxng-src"
            sudo python3 -m venv "/usr/local/searxng/searx-pyenv"
            sudo echo ". /usr/local/searxng/searx-pyenv/bin/activate" \
            && >>  "/usr/local/searxng/.profile"
            sudo -H -u searxng -i
            sudo command -v python && python --version
            sudo pip install -U pip
            sudo pip install -U setuptools
            sudo pip install -U wheel
            sudo pip install -U pyyaml
            cd "/usr/local/searxng/searxng-src"
            sudo pip install -e .
            sudo rm -rf /etc/searxng/settings.yml
            sudo cp ./settings.yml /etc/searxng/
            sudo node index.js

      - name: Always Check
        if: always()
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACTIONS_PAT }}
          event-type: restart
          client-payload: '{"runid": "${{ github.run_id }}"}'
