name: Init

on: push

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Optimize Network Settings
        run: |
            sudo sysctl -w net.core.default_qdisc=fq \
            && sudo sysctl -w net.ipv4.tcp_congestion_control=bbr \
            && sudo sysctl -w net.ipv4.tcp_window_scaling=1 \
            && sudo sysctl -w net.ipv4.ip_forward=1 \
            && sudo sysctl -w net.core.rmem_max=104857600 \
            && sudo sysctl -w net.core.wmem_max=104857600 \
            && sudo sysctl -w net.core.rmem_default=104857600 \
            && sudo sysctl -w net.core.wmem_default=104857600 \
            && sudo sysctl -p

      - name: Install Deps and Initialization
        run: |
            sudo apt-get update && sudo apt-get -y install git curl wget unzip libcurl4-openssl-dev nodejs ffmpeg
            sudo mkdir ./kaybots
            sudo mkdir ./galbots
            sudo git clone https://github.com/TannerGabriel/discord-bot
            sudo git clone https://github.com/nawka12/AiChanBot
            sudo mv ./discord-bot ./kaybots
            sudo mv ./AiChanBot ./kaybots
            sudo touch .env
            sudo chmod -R 777 ./.env
            sudo echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN_MOONAROH }}" >> .env
            sudo mv ./.env ./kaybots/discord-bot
            sudo touch .env
            sudo chmod -R 777 ./.env
            sudo echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN_AICHAN }}" >> .env
            sudo echo "OPENAI_ORG=${{ secrets.OPENAI_ORG }}" >> .env
            sudo echo "OPENAI_KEY=${{ secrets.OPENAI_KEY }}" >> .env
            sudo mv ./.env ./kaybots/AiChanBot
            sudo git clone https://github.com/TannerGabriel/discord-bot
            sudo mv ./discord-bot ./galbots
            sudo touch .env
            sudo chmod -R 777 ./.env
            sudo echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN_EI }}" >> .env
            sudo mv ./.env ./galbots/discord-bot

      - name: Setup galbots
        working-directory: ./galbots/discord-bot
        run: |
            sudo pwd
            sudo npm i
            sudo node index.js &

      - name: Setup Moonaroh
        working-directory: ./kaybots/discord-bot
        run: |
            sudo pwd
            sudo npm i
            sudo node index.js &

      - name: Setup AiChan
        working-directory: ./kaybots/AiChanBot
        continue-on-error: true
        timeout-minutes: 310
        run: |
            sudo pwd
            sudo npm i
            sudo node index.js

      - name: Always Check
        if: always()
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACTIONS_PAT }}
          event-type: restart
          client-payload: '{"runid": "${{ github.run_id }}"}'
